// maisLEAD i18n — pt/en/es (nav + titles portados do protótipo)
export type Lang = "pt" | "en" | "es";

export type ScreenKey =
  | "dashboard" | "manual" | "gplaces" | "cnpj" | "recem" | "leadslist"
  | "crm" | "agenda"
  | "score" | "timeline" | "reports" | "integrations" | "sub" | "settings";

interface Dict {
  nav: Record<string, string>;
  titles: Record<string, [string, string]>;
  auth: Record<string, string>;
  common: Record<string, string>;
  // CRM / Agenda / Funil / WhatsApp / Follow-up / Abas do lead (portados do protótipo)
  crm: { search: string; newLead: string; call: string; whatsapp: string; noLeads: string; leadsCount: string; presets: Record<string, string>; stages: Record<string, string> };
  wa: { msg: string; follow: string };
  docs: { tab: string; dropTitle: string; dropSub: string; empty: string; sample: string };
  links: { tab: string; urlPh: string; notePh: string; add: string; empty: string };
  fulog: { tab: string; addTitle: string; register: string; notePh: string; history: string; empty: string; channels: Record<string, string>; seedWa: string; seedCall: string };
  fup: Record<string, string>;
  agenda: { today: string; week: string; pending: string; newAppt: string; month: string; wk: string; day: string; todayBtn: string; lead: string; leadPh: string; date: string; time: string; notes: string; notesOpt: string; notesPh: string; cancel: string; confirm: string; title: string; at: string; dows: string[]; months: string[]; empty: string };
  funnel: Record<string, string>;
  lead: Record<string, string>;
}

export const DICT: Record<Lang, Dict> = {
  pt: {
    nav: { dashboard: "Dashboard", secPros: "Prospecção", add: "Adicionar Leads", manual: "Entrada Manual", gplaces: "Google Places", cnpj: "Empresas", recem: "Recém-abertas", secMgmt: "Gestão", leads: "Leads", crm: "CRM", agenda: "Agendamentos", score: "Pontuação", timeline: "Linha do tempo", reports: "Relatórios", integrations: "Integrações", sub: "Assinatura", settings: "Configurações" },
    titles: { dashboard: ["Dashboard", "Visão geral da sua prospecção"], manual: ["Entrada Manual", "Cadastre um lead manualmente"], gplaces: ["Google Places", "Extraia leads do Google Maps"], cnpj: ["Empresas", "Consulte por CNPJ ou veja empresas recém-abertas"], recem: ["Empresas Recém-Abertas", "Empresas que abriram recentemente"], leadslist: ["Lista de Leads", "Gerencie e organize seus leads"], crm: ["CRM", "Arraste seus leads pelo funil de vendas"], agenda: ["Agendamentos", "Reuniões e follow-ups agendados"], score: ["Pontuação de Leads", "Priorize os leads mais quentes"], timeline: ["Linha do tempo", "Histórico de atividades dos leads"], reports: ["Relatórios", "Métricas e desempenho da prospecção"], integrations: ["Integrações", "Conecte seus CRMs e ferramentas"], sub: ["Assinatura", "Gerencie seu plano"], settings: ["Configurações", "Preferências e integrações"] },
    auth: { brand: "maisLEAD", tagline: "Prospecção e gestão de leads", signInTitle: "Bem-vindo de volta", signInSub: "Entre na sua conta para continuar", signUpTitle: "Criar conta", signUpSub: "Comece a prospectar em minutos", resetTitle: "Recuperar senha", resetSub: "Enviaremos um link de recuperação por e-mail", name: "Nome", email: "E-mail", password: "Senha", signIn: "Entrar", signUp: "Criar conta", sendReset: "Enviar link", forgot: "Esqueci minha senha", noAccount: "Não tem conta? Cadastre-se", hasAccount: "Já tem conta? Entrar", backToLogin: "Voltar ao login", resetSent: "Link de recuperação enviado. Confira seu e-mail.", checkEmail: "Confirme seu e-mail para ativar a conta.", company: "Empresa", companyPh: "Nome da sua empresa", required: "obrigatório" },
    common: { logout: "Sair", profile: "Perfil", theme: "Tema", language: "Idioma", light: "Claro", dark: "Escuro", loading: "Carregando...", soon: "Em construção", soonSub: "Esta tela chega numa próxima fatia da reconstrução.", error: "Ops, algo deu errado" },
    crm: { search: "Buscar por nome, categoria, cidade ou telefone...", newLead: "+ Criar lead", call: "Ligar", whatsapp: "WhatsApp", noLeads: "Sem leads", leadsCount: "leads", presets: { all: "Todos", hot: "Quentes", score50: "Score 50+", email: "Com e-mail", phone: "Com telefone", nosite: "Sem site" }, stages: { base: "Base", contacted: "Abordado", scheduled: "Agendado", followup: "Follow Up", won: "Convertido", lost: "Perdido" } },
    wa: { msg: "Olá! Falo com a {empresa}? Aqui é da {minhaEmpresa}, gostaria de apresentar uma solução que pode ajudar no seu negócio. Podemos conversar?", follow: "Oi! Aqui é da {minhaEmpresa}, retomando nosso contato com a {empresa}. Ficou alguma dúvida sobre o que conversamos? Sigo à disposição por aqui." },
    docs: { tab: "Documentos", dropTitle: "Anexar documento", dropSub: "Arraste ou clique para enviar (PDF, DOC, imagem)", empty: "Nenhum documento anexado ainda.", sample: "Proposta comercial.pdf" },
    links: { tab: "Links", urlPh: "https://…  (site, drive, proposta)", notePh: "Anotação sobre este link (opcional)", add: "Adicionar link", empty: "Nenhum link salvo ainda." },
    fulog: { tab: "Follow-up", addTitle: "Registrar contato", register: "Registrar", notePh: "O que aconteceu neste contato?", history: "Histórico", empty: "Nenhum follow-up registrado.", channels: { whatsapp: "WhatsApp", call: "Ligação", email: "E-mail", meeting: "Reunião" }, seedWa: "Mensagem enviada pelo WhatsApp — aguardando retorno.", seedCall: "Ligação realizada, sem resposta." },
    fup: { late: "atrasado", todayLbl: "hoje", inLbl: "em", nextTitle: "Próximo follow-up", notSet: "Não agendado", p3: "+3 dias", p7: "+7 dias", tomorrow: "Amanhã", clearDone: "Concluir", days: "dias" },
    agenda: { today: "Hoje", week: "Esta semana", pending: "Pendentes", newAppt: "+ Novo agendamento", month: "Mês", wk: "Semana", day: "Dia", todayBtn: "Hoje", lead: "Lead", leadPh: "Buscar lead por nome ou cidade...", date: "Data", time: "Hora", notes: "Observações", notesOpt: "(opcional)", notesPh: "Adicione uma observação...", cancel: "Cancelar", confirm: "Criar agendamento", title: "Novo agendamento", at: "às", dows: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"], months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"], empty: "Sem agendamentos neste dia" },
    funnel: { title: "Funil de conversão", totalLabel: "Total", contactedLabel: "Abordados", scheduledLabel: "Agendados", followLabel: "Follow Up", lostLabel: "Perdidos", wonLabel: "Convertidos", rateConv: "Taxa de conversão", rateContact: "Taxa de abordagem", rateSched: "Taxa de agendamento", ofTotal: "do total", ofContacted: "dos abordados", ofScheduled: "dos agendados", rateConvSub: "Convertidos / Total", rateContactSub: "Abordados / Total", rateSchedSub: "Agendados / Abordados" },
    lead: { tabDetails: "Detalhes", call: "Ligar", changeStatus: "Mudar status", whyScore: "Por que esta pontuação?", notes: "Anotações", notesPh: "Escreva observações sobre este lead...", verified: "Verificado", invalid: "Não encontrado", online: "Online", pPhone: "Telefone verificado", pEmail: "E-mail válido", pSite: "Website ativo", pAddress: "Endereço completo", pNiche: "Relevância do nicho" },
  },
  en: {
    nav: { dashboard: "Dashboard", secPros: "Prospecting", add: "Add Leads", manual: "Manual Entry", gplaces: "Google Places", cnpj: "Companies", recem: "Newly Opened", secMgmt: "Management", leads: "Leads", crm: "CRM", agenda: "Schedule", score: "Scoring", timeline: "Timeline", reports: "Reports", integrations: "Integrations", sub: "Subscription", settings: "Settings" },
    titles: { dashboard: ["Dashboard", "Overview of your prospecting"], manual: ["Manual Entry", "Add a lead manually"], gplaces: ["Google Places", "Extract leads from Google Maps"], cnpj: ["Companies", "Look up by CNPJ or browse newly opened companies"], recem: ["Newly Opened Companies", "Companies that opened recently"], leadslist: ["Leads List", "Manage and organize your leads"], crm: ["CRM", "Drag your leads through the sales funnel"], agenda: ["Schedule", "Scheduled meetings and follow-ups"], score: ["Lead Scoring", "Prioritize your hottest leads"], timeline: ["Timeline", "Lead activity history"], reports: ["Reports", "Prospecting metrics and performance"], integrations: ["Integrations", "Connect your CRMs and tools"], sub: ["Subscription", "Manage your plan"], settings: ["Settings", "Preferences and integrations"] },
    auth: { brand: "maisLEAD", tagline: "Lead prospecting & management", signInTitle: "Welcome back", signInSub: "Sign in to your account to continue", signUpTitle: "Create account", signUpSub: "Start prospecting in minutes", resetTitle: "Reset password", resetSub: "We'll email you a recovery link", name: "Name", email: "Email", password: "Password", signIn: "Sign in", signUp: "Create account", sendReset: "Send link", forgot: "Forgot password", noAccount: "No account? Sign up", hasAccount: "Have an account? Sign in", backToLogin: "Back to login", resetSent: "Recovery link sent. Check your email.", checkEmail: "Confirm your email to activate the account.", company: "Company", companyPh: "Your company name", required: "required" },
    common: { logout: "Log out", profile: "Profile", theme: "Theme", language: "Language", light: "Light", dark: "Dark", loading: "Loading...", soon: "Coming soon", soonSub: "This screen arrives in a later slice of the rebuild.", error: "Oops, something went wrong" },
    crm: { search: "Search by name, category, city or phone...", newLead: "+ New lead", call: "Call", whatsapp: "WhatsApp", noLeads: "No leads", leadsCount: "leads", presets: { all: "All", hot: "Hot", score50: "Score 50+", email: "With email", phone: "With phone", nosite: "No site" }, stages: { base: "Base", contacted: "Contacted", scheduled: "Scheduled", followup: "Follow Up", won: "Converted", lost: "Lost" } },
    wa: { msg: "Hi! Am I speaking with {empresa}? This is {minhaEmpresa} — I'd love to share a solution that could help your business grow. Can we talk?", follow: "Hi! This is {minhaEmpresa}, following up with {empresa}. Any questions about what we discussed? I'm here whenever you like." },
    docs: { tab: "Documents", dropTitle: "Attach document", dropSub: "Drag or click to upload (PDF, DOC, image)", empty: "No documents attached yet.", sample: "Commercial proposal.pdf" },
    links: { tab: "Links", urlPh: "https://…  (site, drive, proposal)", notePh: "Note about this link (optional)", add: "Add link", empty: "No links saved yet." },
    fulog: { tab: "Follow-up", addTitle: "Log contact", register: "Log", notePh: "What happened in this contact?", history: "History", empty: "No follow-up logged yet.", channels: { whatsapp: "WhatsApp", call: "Call", email: "Email", meeting: "Meeting" }, seedWa: "Message sent via WhatsApp — awaiting reply.", seedCall: "Call made, no answer." },
    fup: { late: "overdue", todayLbl: "today", inLbl: "in", nextTitle: "Next follow-up", notSet: "Not scheduled", p3: "+3 days", p7: "+7 days", tomorrow: "Tomorrow", clearDone: "Complete", days: "days" },
    agenda: { today: "Today", week: "This week", pending: "Pending", newAppt: "+ New appointment", month: "Month", wk: "Week", day: "Day", todayBtn: "Today", lead: "Lead", leadPh: "Search lead by name or city...", date: "Date", time: "Time", notes: "Notes", notesOpt: "(optional)", notesPh: "Add a note...", cancel: "Cancel", confirm: "Create appointment", title: "New appointment", at: "at", dows: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"], months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], empty: "No appointments this day" },
    funnel: { title: "Conversion funnel", totalLabel: "Total", contactedLabel: "Contacted", scheduledLabel: "Scheduled", followLabel: "Follow Up", lostLabel: "Lost", wonLabel: "Converted", rateConv: "Conversion rate", rateContact: "Contact rate", rateSched: "Scheduling rate", ofTotal: "of total", ofContacted: "of contacted", ofScheduled: "of scheduled", rateConvSub: "Converted / Total", rateContactSub: "Contacted / Total", rateSchedSub: "Scheduled / Contacted" },
    lead: { tabDetails: "Details", call: "Call", changeStatus: "Change status", whyScore: "Why this score?", notes: "Notes", notesPh: "Write notes about this lead...", verified: "Verified", invalid: "Not found", online: "Online", pPhone: "Verified phone", pEmail: "Valid email", pSite: "Active website", pAddress: "Complete address", pNiche: "Niche relevance" },
  },
  es: {
    nav: { dashboard: "Panel", secPros: "Prospección", add: "Añadir Leads", manual: "Entrada Manual", gplaces: "Google Places", cnpj: "Empresas", recem: "Recién Abiertas", secMgmt: "Gestión", leads: "Leads", crm: "CRM", agenda: "Agenda", score: "Puntuación", timeline: "Cronología", reports: "Informes", integrations: "Integraciones", sub: "Suscripción", settings: "Configuración" },
    titles: { dashboard: ["Panel", "Resumen de tu prospección"], manual: ["Entrada Manual", "Añade un lead manualmente"], gplaces: ["Google Places", "Extrae leads de Google Maps"], cnpj: ["Empresas", "Consulta por CNPJ o ve empresas recién abiertas"], recem: ["Empresas Recién Abiertas", "Empresas que abrieron recientemente"], leadslist: ["Lista de Leads", "Gestiona y organiza tus leads"], crm: ["CRM", "Arrastra tus leads por el embudo de ventas"], agenda: ["Agenda", "Reuniones y seguimientos programados"], score: ["Puntuación de Leads", "Prioriza tus leads más calientes"], timeline: ["Cronología", "Historial de actividad de leads"], reports: ["Informes", "Métricas y rendimiento de prospección"], integrations: ["Integraciones", "Conecta tus CRMs y herramientas"], sub: ["Suscripción", "Gestiona tu plan"], settings: ["Configuración", "Preferencias e integraciones"] },
    auth: { brand: "maisLEAD", tagline: "Prospección y gestión de leads", signInTitle: "Bienvenido de nuevo", signInSub: "Inicia sesión para continuar", signUpTitle: "Crear cuenta", signUpSub: "Empieza a prospectar en minutos", resetTitle: "Recuperar contraseña", resetSub: "Te enviaremos un enlace de recuperación", name: "Nombre", email: "Email", password: "Contraseña", signIn: "Entrar", signUp: "Crear cuenta", sendReset: "Enviar enlace", forgot: "Olvidé mi contraseña", noAccount: "¿Sin cuenta? Regístrate", hasAccount: "¿Ya tienes cuenta? Entra", backToLogin: "Volver al inicio", resetSent: "Enlace de recuperación enviado. Revisa tu email.", checkEmail: "Confirma tu email para activar la cuenta.", company: "Empresa", companyPh: "Nombre de tu empresa", required: "obligatorio" },
    common: { logout: "Salir", profile: "Perfil", theme: "Tema", language: "Idioma", light: "Claro", dark: "Oscuro", loading: "Cargando...", soon: "Próximamente", soonSub: "Esta pantalla llega en una fase posterior de la reconstrucción.", error: "Ups, algo salió mal" },
    crm: { search: "Buscar por nombre, categoría, ciudad o teléfono...", newLead: "+ Crear lead", call: "Llamar", whatsapp: "WhatsApp", noLeads: "Sin leads", leadsCount: "leads", presets: { all: "Todos", hot: "Calientes", score50: "Score 50+", email: "Con email", phone: "Con teléfono", nosite: "Sin sitio" }, stages: { base: "Base", contacted: "Contactado", scheduled: "Agendado", followup: "Follow Up", won: "Convertido", lost: "Perdido" } },
    wa: { msg: "¡Hola! ¿Hablo con {empresa}? Le escribo de {minhaEmpresa}, me gustaría presentarle una solución que puede ayudar a su negocio. ¿Podemos hablar?", follow: "¡Hola! Le escribo de {minhaEmpresa}, retomando nuestro contacto con {empresa}. ¿Quedó alguna duda de lo que hablamos? Sigo a su disposición por aquí." },
    docs: { tab: "Documentos", dropTitle: "Adjuntar documento", dropSub: "Arrastra o haz clic para subir (PDF, DOC, imagen)", empty: "Ningún documento adjunto todavía.", sample: "Propuesta comercial.pdf" },
    links: { tab: "Enlaces", urlPh: "https://…  (sitio, drive, propuesta)", notePh: "Nota sobre este enlace (opcional)", add: "Agregar enlace", empty: "Ningún enlace guardado todavía." },
    fulog: { tab: "Follow-up", addTitle: "Registrar contacto", register: "Registrar", notePh: "¿Qué pasó en este contacto?", history: "Historial", empty: "Ningún follow-up registrado.", channels: { whatsapp: "WhatsApp", call: "Llamada", email: "Correo", meeting: "Reunión" }, seedWa: "Mensaje enviado por WhatsApp — esperando respuesta.", seedCall: "Llamada realizada, sin respuesta." },
    fup: { late: "atrasado", todayLbl: "hoy", inLbl: "en", nextTitle: "Próximo seguimiento", notSet: "No programado", p3: "+3 días", p7: "+7 días", tomorrow: "Mañana", clearDone: "Completar", days: "días" },
    agenda: { today: "Hoy", week: "Esta semana", pending: "Pendientes", newAppt: "+ Nueva cita", month: "Mes", wk: "Semana", day: "Día", todayBtn: "Hoy", lead: "Lead", leadPh: "Buscar lead por nombre o ciudad...", date: "Fecha", time: "Hora", notes: "Notas", notesOpt: "(opcional)", notesPh: "Añade una nota...", cancel: "Cancelar", confirm: "Crear cita", title: "Nueva cita", at: "a las", dows: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"], months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"], empty: "Sin citas este día" },
    funnel: { title: "Embudo de conversión", totalLabel: "Total", contactedLabel: "Abordados", scheduledLabel: "Agendados", followLabel: "Follow Up", lostLabel: "Perdidos", wonLabel: "Convertidos", rateConv: "Tasa de conversión", rateContact: "Tasa de abordaje", rateSched: "Tasa de agendamiento", ofTotal: "del total", ofContacted: "de abordados", ofScheduled: "de agendados", rateConvSub: "Convertidos / Total", rateContactSub: "Abordados / Total", rateSchedSub: "Agendados / Abordados" },
    lead: { tabDetails: "Detalles", call: "Llamar", changeStatus: "Cambiar estado", whyScore: "¿Por qué esta puntuación?", notes: "Notas", notesPh: "Escribe notas sobre este lead...", verified: "Verificado", invalid: "No encontrado", online: "En línea", pPhone: "Teléfono verificado", pEmail: "Email válido", pSite: "Sitio web activo", pAddress: "Dirección completa", pNiche: "Relevancia del nicho" },
  },
};
